<?php

namespace App\Console\Commands;

use App\Model\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class CreateFirstAdminUser extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:create-first-admin
                            {--name= : Name des Admin-Benutzers}
                            {--email= : E-Mail-Adresse des Admin-Benutzers}
                            {--password= : Passwort des Admin-Benutzers}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Legt den ersten Admin-Benutzer bei einer frischen Installation an';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        // Prüfen ob bereits ein Admin existiert
        if (User::role('Administrator')->exists()) {
            $this->error('Es existiert bereits mindestens ein Administrator-Benutzer. Abbruch.');
            return self::FAILURE;
        }

        $this->info('=== Erster Admin-Benutzer anlegen ===');
        $this->newLine();

        // Name ermitteln
        $name = $this->option('name');
        if (empty($name)) {
            $name = $this->ask('Name des Admin-Benutzers', config('mail.from.name', 'Administrator'));
        }

        // E-Mail ermitteln
        $email = $this->option('email');
        if (empty($email)) {
            $email = $this->ask('E-Mail-Adresse', config('mail.from.address'));
        }

        // E-Mail-Validierung
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $this->error("Die E-Mail-Adresse \"{$email}\" ist ungültig.");
            return self::FAILURE;
        }

        // Prüfen ob E-Mail bereits vergeben ist
        if (User::where('email', $email)->exists()) {
            $this->error("Ein Benutzer mit der E-Mail-Adresse \"{$email}\" existiert bereits.");
            return self::FAILURE;
        }

        // Passwort ermitteln
        $password = $this->option('password');
        if (empty($password)) {
            $password = $this->secret('Passwort (leer lassen für auto-generiertes Passwort)');
        }

        $autoGenerated = false;
        if (empty($password)) {
            $password = $this->generateSecurePassword();
            $autoGenerated = true;
        }

        // Zusammenfassung anzeigen
        $this->newLine();
        $this->table(
            ['Feld', 'Wert'],
            [
                ['Name', $name],
                ['E-Mail', $email],
                ['Passwort', $autoGenerated ? $password . ' (auto-generiert)' : '***'],
                ['Rolle', 'Administrator'],
            ]
        );

        if (!$this->confirm('Admin-Benutzer anlegen?', true)) {
            $this->warn('Abgebrochen.');
            return self::FAILURE;
        }

        // Rollen & Berechtigungen sicherstellen
        $this->ensureAdministratorRoleExists();

        // Benutzer anlegen
        $user = User::create([
            'name'               => $name,
            'email'              => $email,
            'password'           => Hash::make($password),
            'email_verified_at'  => now(),
            'changePassword'     => $autoGenerated,
            'benachrichtigung'   => 1,
            'is_active'          => true,
        ]);

        $user->syncRoles(['Administrator']);

        $this->newLine();
        $this->info("✓ Admin-Benutzer erfolgreich angelegt (ID: {$user->id}).");

        if ($autoGenerated) {
            $this->newLine();
            $this->warn('Das auto-generierte Passwort lautet:');
            $this->line("  <fg=yellow;options=bold>{$password}</>");
            $this->warn('Bitte notiere dieses Passwort – es wird nicht erneut angezeigt!');
        }

        $this->newLine();

        return self::SUCCESS;
    }

    /**
     * Stellt sicher, dass die Administrator-Rolle existiert.
     * Legt sie an, falls sie noch nicht vorhanden ist.
     */
    private function ensureAdministratorRoleExists(): void
    {
        if (!Role::where('name', 'Administrator')->where('guard_name', 'web')->exists()) {
            $this->line('Administrator-Rolle wird angelegt...');
            Role::create(['name' => 'Administrator', 'guard_name' => 'web']);
        }
    }

    /**
     * Generiert ein sicheres Zufallspasswort.
     */
    private function generateSecurePassword(int $length = 16): string
    {
        $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*';
        $password = '';
        $max = strlen($chars) - 1;
        for ($i = 0; $i < $length; $i++) {
            $password .= $chars[random_int(0, $max)];
        }
        return $password;
    }
}

