<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\createNachrichtRequest
 */
class createNachrichtRequestTest extends TestCase
{
    /** @var \App\Http\Requests\createNachrichtRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\createNachrichtRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'header' => [
                'required',
            ],
            'news' => [
                'required',
            ],
            'gruppen' => [
                'required',
            ],
            'password' => [
                'required_with:urgent',
            ],
            'type' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
