<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\createDiscussionRequest
 */
class createDiscussionRequestTest extends TestCase
{
    /** @var \App\Http\Requests\createDiscussionRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\createDiscussionRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'header' => [
                'required',
                'string',
            ],
            'text' => [
                'required',
            ],
            'sticky' => [
                'required',
                'boolean',
            ],
        ], $actual);
    }

    // test cases...
}
