<?php

namespace Tests\Unit\Http\Requests;

use App\Model\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Str;
use Tests\FormRequestTestCase;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\CreateChildRequest
 */
class CreateChildRequestTest extends FormRequestTestCase
{
    use RefreshDatabase;

    private $subject;
    private $rules;
    private $validator;

    protected function setUp(): void
    {
        parent::setUp();
        $this->subject = new \App\Http\Requests\CreateChildRequest();
        $this->rules = $this->subject->rules();

    }

    /**
     * @test
     */
    public function no_authorize_without_user()
    {
        $actual = $this->subject->authorize();
        $this->assertFalse($actual);
    }

    /**
     * @test
     */
    public function authorize_with_user()
    {
        $user = User::factory()->make();
        $this->actingAs($user);
        $actual = $this->subject->authorize();
        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'child' => [
                'required',
                'string',
            ],
        ], $actual);
    }


    /**
     * @test
     */
    public function child_is_requried()
    {
        $string = Str::random();
        $this->assertFalse($this->validateField('child', '', $this->rules));
        $this->assertFalse($this->validateField('child', [$string], $this->rules));
        $this->assertTrue($this->validateField('child', $string, $this->rules));
    }
}
