<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\CreateListeRequest
 */
class CreateListeRequestTest extends TestCase
{
    /** @var \App\Http\Requests\CreateListeRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\CreateListeRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'listenname' => [
                'required',
                'string',
            ],
            'type' => [
                'required',
                'in:termin,eintrag',
            ],
            'visible_for_all' => [
                'required',
                'boolean',
            ],
            'multiple' => [
                'required',
                'boolean',
            ],
            'active' => [
                'required',
                'boolean',
            ],
            'ende' => [
                'required',
                'date',
            ],
        ], $actual);
    }

    // test cases...
}
