<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\CreateTerminRequest
 */
class CreateTerminRequestTest extends TestCase
{
    /** @var \App\Http\Requests\CreateTerminRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\CreateTerminRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'terminname' => [
                'required',
                'string',
            ],
            'start' => [
                'required',
                'date',
                'before:ende',
            ],
            'ende' => [
                'required',
                'date',
                'after:start',
            ],
            'gruppen' => [
                'required',
            ],
            'public' => [
                'nullable',
                'integer',
                'min:0',
                'max:1',
            ],
        ], $actual);
    }

    // test cases...
}
