<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\createAbfrageRequest
 */
class createAbfrageRequestTest extends TestCase
{
    /** @var \App\Http\Requests\createAbfrageRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\createAbfrageRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'description' => [
                'required',
                'string',
            ],
            'ende' => [
                'required',
                'date',
                'after:today',
            ],
            'max_number' => [
                'required',
                'integer',
                'min:0',
            ],
            'options' => [
                'required',
                'array',
                'min:2',
            ],
            'types' => [
                'required',
                'array',
                'min:2',
            ],
            'empfaenger' => [
                'required',
                'exists:users,email',
            ],
            'pflicht' => [
                'integer',
                'nullable',
                'max:1',
            ],
            'multiple' => [
                'integer',
                'nullable',
                'max:1',
            ],
        ], $actual);
    }

    // test cases...
}
