<?php

namespace Tests\Unit\Http\Requests;

use App\Http\Requests\createDiscussionRequest;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\FormRequestTestCase;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\createDiscussionRequest
 */
class createDiscussionRequestTest extends FormRequestTestCase
{
    use RefreshDatabase;

    private $subject;
    private $rules;
    private $validator;

    protected function setUp(): void
    {
        parent::setUp();
        $this->subject = new createDiscussionRequest();
        $this->rules = $this->subject->rules();

    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'header' => [
                'required',
                'string',
            ],
            'text' => [
                'required',
            ],
            'sticky' => [
                'required',
                'boolean',
            ],
        ], $actual);
    }

    // test cases...
}
