<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\KrankmeldungRequest
 */
class KrankmeldungRequestTest extends TestCase
{
    /** @var \App\Http\Requests\KrankmeldungRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\KrankmeldungRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'name' => [
                'required',
                'string',
            ],
            'kommentar' => [
                'required',
                'string',
            ],
            'start' => [
                'required',
                'date_format:Y-m-d',
            ],
            'ende' => [
                'required',
                'date_format:Y-m-d',
            ],
        ], $actual);
    }

    // test cases...
}
