<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\ReinigungsRequest
 */
class ReinigungsRequestTest extends TestCase
{
    /** @var \App\Http\Requests\ReinigungsRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\ReinigungsRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'users_id' => [
                'required',
                'exists:users,id',
            ],
            'aufgabe' => [
                'required',
                'exists:reinigungs_tasks,id',
            ],
            'bemerkung' => [
                'nullable',
                'string',
            ],
            'datum' => [
                'required',
                'date',
            ],
        ], $actual);
    }

    // test cases...
}
