<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\StoreListeTerminRequest
 */
class StoreListeTerminRequestTest extends TestCase
{
    /** @var \App\Http\Requests\StoreListeTerminRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\StoreListeTerminRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'termin' => [
                'required',
                'date',
            ],
            'zeit' => [
                'required',
                'date_format:H:i',
            ],
            'comment' => [
                'string',
                'nullable',
            ],
            'weekly' => [
                'integer',
                'max:1',
                'nullable',
            ],
            'repeat' => [
                'integer',
                'min:1',
                'nullable',
            ],
        ], $actual);
    }

    // test cases...
}
