<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\StorePollRequest
 */
class StorePollRequestTest extends TestCase
{
    /** @var \App\Http\Requests\StorePollRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\StorePollRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'poll_name' => [
                'required',
                'string',
            ],
            'description' => [
                'nullable',
                'string',
            ],
            'ends' => [
                'required',
                'date',
                'after:today',
            ],
            'max_number' => [
                'required',
                'integer',
                'min:1',
            ],
            'options' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
