<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\StorePushRequest
 */
class StorePushRequestTest extends TestCase
{
    /** @var \App\Http\Requests\StorePushRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\StorePushRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'endpoint' => [
                'required',
            ],
            'keys.auth' => [
                'required',
            ],
            'keys.p256dh' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
