<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ChangelogController
 */
class ChangelogControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('changelog.create'));

        $response->assertOk();
        $response->assertViewIs('changelog.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('changelog.index'));

        $response->assertOk();
        $response->assertViewIs('changelog.index');
        $response->assertViewHas('changelogs');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('changelog.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('changelog'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\ChangelogController::class,
            'store',
            \App\Http\Requests\CreateChangelogRequest::class
        );
    }

    // test cases...
}
