<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ElternratController
 */
class ElternratControllerTest extends TestCase
{
    /**
     * @test
     */
    public function add_file_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('elternrat/add/file');

        $response->assertOk();
        $response->assertViewIs('elternrat.createFile');
        $response->assertViewHas('groups');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('elternrat.create'));

        $response->assertOk();
        $response->assertViewIs('elternrat.createDiscussion');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_comment_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete('elternrat/comment/{comment}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_file_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete('elternrat/file/{file}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('elternrat.edit', ['elternrat' => $elternrat]));

        $response->assertOk();
        $response->assertViewIs('elternrat.editDiscussion');
        $response->assertViewHas('beitrag');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('elternrat.index'));

        $response->assertOk();
        $response->assertViewIs('elternrat.index');
        $response->assertViewHas('themen');
        $response->assertViewHas('directories');
        $response->assertViewHas('users');
        $response->assertViewHas('group');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('elternrat.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('elternrat'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\ElternratController::class,
            'store',
            \App\Http\Requests\createDiscussionRequest::class
        );
    }

    /**
     * @test
     */
    public function store_comment_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('beitrag/{discussion}/comment/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_file_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('elternrat/file', [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('elternrat'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('elternrat.update', ['elternrat' => $elternrat]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('elternrat'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\ElternratController::class,
            'update',
            \App\Http\Requests\createDiscussionRequest::class
        );
    }

    // test cases...
}
