<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\FeedbackController
 */
class FeedbackControllerTest extends TestCase
{
    /**
     * @test
     */
    public function send_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('feedback', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function send_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\FeedbackController::class,
            'send',
            \App\Http\Requests\KontaktRequest::class
        );
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('feedback');

        $response->assertOk();
        $response->assertViewIs('feedback.show');
        $response->assertViewHas('mitarbeiter');
        $response->assertViewHas('emails');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_mail_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('feedback/show/{mail}');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
