<?php

namespace Tests\Feature\Http\Controllers;

use App\Model\User;
use Database\Factories\Model\GroupFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\GroupsController
 */
class GroupsControllerTest extends TestCase
{
    use RefreshDatabase;
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {

        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()
            ->hasGroups(3)
            ->create();

        $this->actingAs($user);

        $response = $this->get('groups');

        $response->assertOk();
        $response->assertViewIs('groups.index');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('groups', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
