<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ICalController
 */
class ICalControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_i_cal_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{uuid}/ical');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function public_i_cal_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('ical/publicEvents');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
