<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ImportController
 */
class ImportControllerTest extends TestCase
{
    /**
     * @test
     */
    public function import_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('users/import', [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('users'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function import_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('users/import');

        $response->assertOk();
        $response->assertViewIs('user.import');

        // TODO: perform additional assertions
    }

    // test cases...
}
