<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LosungController
 */
class LosungControllerTest extends TestCase
{
    /**
     * @test
     */
    public function import_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('settings/losungen/import', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function import_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\LosungController::class,
            'import',
            \App\Http\Requests\ImportLosungenRequest::class
        );
    }

    /**
     * @test
     */
    public function import_view_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('settings/losungen/import');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
