<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ReactionController
 */
class ReactionControllerTest extends TestCase
{
    /**
     * @test
     */
    public function react_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('posts/{post}/react/{reaction}');

        $response->assertRedirect(url()->previous().'#'.$post->id);

        // TODO: perform additional assertions
    }

    // test cases...
}
