<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ReinigungController
 */
class ReinigungControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('reinigung/create/{Bereich}/{Datum}');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('reinigung');

        $response->assertOk();
        $response->assertViewIs('reinigung.show');
        $response->assertViewHas('Bereiche');
        $response->assertViewHas('Familien');
        $response->assertViewHas('datum');
        $response->assertViewHas('user');
        $response->assertViewHas('ende');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('reinigung/{Bereich}', [
            // TODO: send request data
        ]);

        $response->assertRedirect(to(url('reinigung')));

        // TODO: perform additional assertions
    }

    // test cases...
}
