<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\RueckmeldungenController
 */
class RueckmeldungenControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_image_rueckmeldung_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('rueckmeldungen/{posts}/createImageUpload');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete('rueckmeldung/{rueckmeldung}');

        $response->assertOk();
        $this->assertDeleted($$rueckmeldung);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('rueckmeldung/{posts_id}/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(to(url('/home')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put('rueckmeldung/{posts_id}/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(to(url('home')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_commentable_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('rueckmeldungen/{rueckmeldungen}/commentable');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
