<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SearchController
 */
class SearchControllerTest extends TestCase
{
    /**
     * @test
     */
    public function search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('search', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('search.result');
        $response->assertViewHas('nachrichten');
        $response->assertViewHas('archiv');
        $response->assertViewHas('user');
        $response->assertViewHas('gruppen');
        $response->assertViewHas('Suche');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function search_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\SearchController::class,
            'search',
            \App\Http\Requests\searchRequest::class
        );
    }

    // test cases...
}
