<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UserRueckmeldungenController
 */
class UserRueckmeldungenControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('userrueckmeldung/edit/{userRueckmeldungen}');

        $response->assertOk();
        $response->assertViewIs('userrueckmeldung.edit');
        $response->assertViewHas('Rueckmeldung');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function send_rueckmeldung_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('rueckmeldung/{posts_id}', [
            // TODO: send request data
        ]);

        $response->assertRedirect(url('/home#'.$post_id->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put('userrueckmeldung/{userRueckmeldungen}', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
