<?php

namespace Tests\Feature\Http\Controllers\Auth;

use App\Model\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Auth\ExpiredPasswordController
 */
class ExpiredPasswordControllerTest extends TestCase
{
    use RefreshDatabase;
    /**
     * @test
     */
    public function expired_returns_an_ok_response_if_changePassword_needed()
    {
        $user = User::factory()->make([
            'changePassword'=>1
        ]);

        $this->actingAs($user);

        $response = $this->get(route('password.expired'));

        $response->assertOk();
        $response->assertViewIs('auth.passwords.expired');

    }

    /**
     * @test
     */
    public function expired_returns_an_redirect_response_if_no_changePassword_needed()
    {
        $user = User::factory()->make([
            'changePassword'=>0
        ]);

        $this->actingAs($user);

        $response = $this->get(route('password.expired'));

        $response->assertRedirect(url('/'));
    }

    /**
     * @test
     */
    public function post_expired_returns_redirect_withError_response_if_Password_wrong()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->make([
            'changePassword'=>1
        ]);

        $this->actingAs($user);

        $response = $this->post(route('password.post_expired'), [
            'current_password'=> null
        ]);

        $response->assertRedirect(withErrors(['current_password' => 'Current password is not correct']));

        // TODO: perform additional assertions
    }

    // test cases...
}
